### ISSUE TITLE
no attribute 'pretrain_ema'

### ISSUE THREAD

**Issue by wg-li** [jorghyq2016/FedHSSL#1]
Hello,
Nice work. Thanks for the code, but I got this error:

File "/data/nfs/user/liwg/vfl/fedhssl/FedHSSL/pretrain_template.py", line 142, in update_local_top_model
    if self.args.pretrain_ema > 0.0:
AttributeError: 'Namespace' object has no attribute 'pretrain_ema'

I didn't find "pretrain_ema" defined in the code. Could you please check it?

**Comment by jorghyq2016** [comment]
Hi,

sorry for the inconvience. The "pretrain_ema" is an old parameter. Now it should be fine.
Let me know if you have other problems.
Best.

**Comment by yankang18** [comment]
issue addressed

**Comment by wg-li** [comment]
thanks!
